### ISSUE TITLE
Download Link not working

### ISSUE THREAD

**Issue by ghost** [intersystems-ru/cache-visual-editor#1]
Hi

The Install link leads to a page not found response.

https://github.com/intersystems-ru/objectscript-visual-editor/releases
![image](https://user-images.githubusercontent.com/6480047/58147143-73e79080-7c59-11e9-82a2-468b27545425.png)

**Comment by nikitaeverywhere** [comment]
Hello Eric! Thanks for reporting! Now fixed. See this thread: https://community.intersystems.com/post/objectscript-visual-editor-github-repo

We would love to hear your feedback. Thanks!
